services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: 2G
      VERSION: 1.21.8
      DIFFICULTY: normal
      MAX_PLAYERS: 25
      MODE: survival
    volumes:
      - ./data:/data